name: Deploy Website

on:
  push:
    branches:
      - main   # change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Copy files to remote server (temporary directory)
      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*.html"
          target: "/home/${{ secrets.USER }}/deploy/"

      # Step 2: SSH into server and move files into nginx directory
      - name: Move files to nginx html folder
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo mv /home/${{ secrets.USER }}/deploy/*.html /usr/share/nginx/html/
            sudo systemctl restart nginx
