name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/xops_ec2
          chmod 600 ~/.ssh/xops_ec2
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Sync files to EC2
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/xops_ec2 -o StrictHostKeyChecking=yes" \
            src/ ${{ secrets.SSH_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/xopsapp/

      - name: Reload NGINX
        run: |
          ssh -i ~/.ssh/xops_ec2 ${{ secrets.SSH_USERNAME }}@${{ secrets.EC2_HOST }} \
            "sudo nginx -t && sudo systemctl reload nginx"
